research_task:
  description: >
    Conduzir uma pesquisa aprofundada sobre {company}
    Traga dados financeiros, notícias recentes e relevantes e principais executivos.
    Traga também notícias relacionadas as áreas de atuação da empresa.
    Se houver um site de relações com investidores, busque neste site informações sobre a empresa.
    Sempre busque dados mais recentes.
  expected_output: >
    Lista de tópicos com informações relevantes sobre a empresa pesquisada.

reporting_task:
  description: >
    Consolide as informações coletadas pelo pesquisador em um relatório detalhado.
    Ao final realize o envio do email com o relatório em formato HTML.
  expected_output: >
    Relatório, em HTML, objetivo que traga as seguintes informações:
    - Áreas de atuação
    - Notícias recentes
    - Principais desafios
    - Principais anúncios
    - Sugestão de conteúdo para abertura de conversas e criação de rapport.
    Formate a resposta como HTML, sem '```'
